# Generated by Django 6.1.1 on 2026-09-07 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tote_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PickSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='picks.station')),
            ],
        ),
        migrations.CreateModel(
            name='PickTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('picked', 'Picked'), ('unscannable', 'Unscannable'), ('missing', 'Missing'), ('problem_tote', 'Problem Tote')], default='pending', max_length=20)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picks.item')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='picks.picksession')),
                ('destination_tote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_tasks', to='picks.tote')),
                ('source_tote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_tasks', to='picks.tote')),
            ],
        ),
    ]
