# Generated by Django 6.1.1 on 2026-09-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
